# Generated by Django 6.0 on 2025-12-17 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('is_bot_game', models.BooleanField(default=False)),
                ('bot_color', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black')], max_length=5, null=True)),
                ('current_turn', models.CharField(default='white', max_length=5)),
                ('board_state', models.JSONField(default=dict)),
                ('move_history', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chess_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chess_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
